# Generated by Django 3.1.6 on 2022-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-last_used']},
        ),
        migrations.AddField(
            model_name='stockdata',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='relate_stock',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='relate_strategy',
            field=models.TextField(blank=True),
        ),
    ]
