# Generated by Django 3.1.6 on 2022-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20220320_0315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedstrategies",
            name="strategy",
            field=models.TextField(),
        ),
    ]
