# Generated by Django 3.1.6 on 2022-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220315_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='last_used',
            field=models.DateTimeField(),
        ),
    ]
